import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import Button from "@/components/Button";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cresce Cuts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menuList = [
    { name: "Lista de descontos", link: "/" },
    { name: "Descontos", link: "/discounts" },
    { name: "Lojas", link: "/stores" },
    { name: "Categorias", link: "/categories" },
    { name: "Usuários", link: "/users" },
    { name: "Configurações", link: "/settings" },
  ];

  return (
    <html lang="en">
      <body className={rubik.className}>
        <div className="flex">
          <nav className="flex flex-col items-center py-4 bg-background-menu w-[256px] fixed h-full">
            <Image src="/VALE-VANTAGENS.svg" alt="Vale Vantagens" width={150} height={80} />
            <ul className="flex flex-col p-4 gap-2 text-white font-normal text-xs w-full">
              {
                menuList.map((item, index) => (
                  <li key={index}>
                    <a href={item.link} className="flex justify-between items-center">
                        <p>{item.name}</p>
                        <Image src="/CHEVRON.svg" alt={item.name} width={20} height={30} />
                    </a>
                  </li>
                ))
              }
            </ul>
          </nav>
          <main className="w-screen bg-background overflow-y-auto ml-[256px]">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
